on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: App

env:
  RELEASE: true

jobs:

  cancel-others:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-android:
    runs-on: ubuntu-latest
    name: Build Android
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Rust Android Setup
        run: cargo make setup-android

      - uses: subosito/flutter-action@v2
        name: "Set up flutter"
        with:
          channel: 'stable'

      - name: Build Android FFI
        run: cargo make --profile release android-arm

      - name: Ensure ffi-interface is up to date
        run: git diff --exit-code  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart

      - run: flutter build apk --target-platform android-arm64 --release
        working-directory: ./app

  build-ios:
    runs-on: macos-latest
    name: Build iOS
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - uses: Swatinem/rust-cache@v1
      - run: cargo make setup-ios
      - uses: subosito/flutter-action@v2
        name: "Set up flutter"
        with:
          channel: 'stable'
      - name: Build iOS FFI
        run: cargo make --profile release  ios
      - name: Ensure ffi-interface is up to date
        run: git diff --exit-code  effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart
      - run: flutter build ios --release --no-codesign
        working-directory: ./app
